### ISSUE TITLE
CDN Uptime status link

### ISSUE THREAD

**Issue by obeho** [cdnjs/static-website#72] opened 2021-02-20 07:02 UTC
The [website](https://cdnjs.com/) under Status column links to the CDN uptime monitor to `http://stats.pingdom.com/4jg86a2wqei0?utm_source=cdnjs&utm_medium=cdnjs_link&utm_campaign=cdnjs_footer`.

Its better to link the secure version instead, `https://secure-stats.pingdom.com/4jg86a2wqei0`.

**Comment by MattIPv4** [comment] 2021-02-28 00:57
👋 Thanks for sharing this -- we're actually going to be moving away from Pingdom shortly, so I'll hold off on resolving this for now. The link will likely soon be removed from the site completely in favour of our main status page.

**Comment by MattIPv4** [comment] 2021-03-03 10:53
Linked now removed -- more metrics will be shared via status.cdnjs.com soon :)

**Closed by MattIPv4** 2021-03-03 10:53 UTC

**Comment by obeho** [comment] 2021-03-03 14:30
Please correct me if I'm wrong, if `cdnjs.com` went down for some reason, how do we check the status? `status.cdnjs.com` would be down too at that time, right?

**Comment by MattIPv4** [comment] 2021-03-03 14:31
They are hosted on completely different services. The only situation in which both would be down if is DNS resolution was failing.

**Comment by obeho** [comment] 2021-03-03 14:53
Yes, that is the most common way of "going down" not a DDoS.

**Comment by MattIPv4** [comment] 2021-03-03 14:55
We've never had DNS resolution issues be the cause of an outage for cdnjs.com -- the most common issue that would take the site down by far would be issues with the site host.

It's also worth noting that the core CDN service we provide is on a separate domain, cdnjs.cloudflare.com

**Comment by obeho** [comment] 2021-03-03 15:07
> issues with the site host.

I guess I should've said, common way which are not beyond your control. 😁

And both are tied to the same CloudFlare account, I presume?

**Comment by MattIPv4** [comment] 2021-03-03 15:08
No, they are in completely different accounts -- cdnjs.cloudflare.com is very isolated from anything else cdnjs related.
